<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [1]:
#import piplite
#await piplite.install(['folium'])
#await piplite.install(['pandas'])

In [2]:
%pip install folium

Collecting folium
  Using cached folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Using cached branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from folium) (2.3.1)
Requirement already satisfied: requests in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from folium) (2.32.5)
Collecting xyzservices (from folium)
  Downloading xyzservices-2026.9.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\desktop\sample_project_1\env\lib\site-packages (from requests->folium) (2025.8.3)
Using cached folium-0.20.0-py2.py3-none-any.whl (113 kB)
Using cached branca-0.8.2-py3-none-any.whl (26 kB)
Downloading xyzservices-2026.9.1-py3-none-any.whl (98 kB)
Installing collected packages: xyzservices, branca, folium

   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   ---------------------------------------- 3/3 [folium]

Successfully installed branca-0.8.2 folium-0.20.0 xyzservices-2026.9.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import folium
import pandas as pd

In [4]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

In [5]:
spacex_df = pd.read_csv("spacex_launch_geo.csv")

print("Dataset shape:", spacex_df.shape)
print("\nColumns:")
print(spacex_df.columns.tolist())

display(spacex_df.head())

Dataset shape: (56, 14)

Columns:
['Flight Number', 'Date', 'Time (UTC)', 'Booster Version', 'Launch Site', 'Payload', 'Payload Mass (kg)', 'Orbit', 'Customer', 'Mission Outcome', 'Landing Outcome', 'class', 'Lat', 'Long']

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Mission Outcome,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),Success,No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356

In [6]:
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]

launch_sites_df = (
    spacex_df.groupby('Launch Site', as_index=False)
    .first()
)

launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]

display(launch_sites_df)

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610746

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [7]:
## Task 1: Mark all launch sites on a map

import pandas as pd
import folium

spacex_df = pd.read_csv("spacex_launch_geo.csv")

display(spacex_df.head())

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Mission Outcome,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),Success,No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356

In [8]:
spacex_df = spacex_df[
    ["Launch Site", "Lat", "Long", "class"]
]

launch_sites_df = (
    spacex_df.groupby("Launch Site", as_index=False)
    .first()
)

launch_sites_df = launch_sites_df[
    ["Launch Site", "Lat", "Long"]
]

display(launch_sites_df)

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610746

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

In [9]:
# Create a map centred near the launch sites

site_map = folium.Map(
    location=[29.559684, -95.083097],
    zoom_start=5
)

# Add a marker for each launch site
for _, site in launch_sites_df.iterrows():

    folium.Circle(
        location=[site["Lat"], site["Long"]],
        radius=1000,
        color="blue",
        fill=True,
        fill_color="blue",
        fill_opacity=0.5,
        popup=site["Launch Site"]
    ).add_to(site_map)

    folium.Marker(
        location=[site["Lat"], site["Long"]],
        popup=site["Launch Site"],
        icon=folium.Icon(color="blue", icon="info-sign")
    ).add_to(site_map)

# Display the map
site_map

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [10]:
site_map.save("spacex_launch_sites_map.html")

print("Launch site map saved successfully!")

Launch site map saved successfully!

In [ ]:
# Download and read the `spacex_launch_geo.csv`
#from js import fetch
#import io

#URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
#resp = await fetch(URL)
#spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
#spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [11]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610746

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [15]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

site_map

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [13]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [18]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

In [20]:
# Extract unique SpaceX launch sites and coordinates

launch_sites = (
    spacex_df.groupby("Launch Site", as_index=False)
    .first()
)

launch_sites = launch_sites[["Launch Site", "Lat", "Long"]]

display(launch_sites)

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610746

In [21]:
# TASK 1: Mark all SpaceX launch sites

# Initialize the map
site_map = folium.Map(
    location=nasa_coordinate,
    zoom_start=5
)

# Add a circle and text marker for each launch site
for _, site in launch_sites.iterrows():

    coordinate = [site["Lat"], site["Long"]]
    site_name = site["Launch Site"]

    # Add a circle with a popup
    circle = folium.Circle(
        location=coordinate,
        radius=1000,
        color="#d35400",
        fill=True
    ).add_child(
        folium.Popup(site_name)
    )

    # Add a text label
    marker = folium.Marker(
        location=coordinate,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12px; color:#d35400;"><b>{site_name}</b></div>'
        )
    )

    site_map.add_child(circle)
    site_map.add_child(marker)

# Display the completed map
site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

## Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

### Question 1: Are all launch sites in proximity to the Equator?

Answer: No, not all launch sites are very close to the Equator.
The Florida launch sites are around 28–29° north latitude, while Vandenberg is approximately 34–35° north. They are all in the Northern Hemisphere, but they are not on the Equator.
Lower-latitude launch sites can benefit from Earth's rotational speed, particularly for eastward launches. However, launch-site selection also depends on mission requirements and orbital inclination.

Question 2: Are all launch sites very close to the coast?
Answer: Yes. The SpaceX launch sites in this dataset are located close to coastlines.
The Florida sites are near the Atlantic Ocean, while Vandenberg is near the Pacific Ocean.
Coastal locations provide access to launch trajectories over large ocean areas, helping reduce risks to populated regions from falling rocket stages and debris.

Conclusion:
Launch Site Location Analysis
The Folium map shows that SpaceX launch sites are located in coastal regions of the United States. Cape Canaveral and Kennedy Space Center are situated along Florida's Atlantic coast, while Vandenberg is located along California's Pacific coast.
Although the launch sites are not directly on the Equator, the Florida sites are at lower latitudes than Vandenberg. This can offer advantages for certain orbital launches because of Earth's rotation.
The coastal locations also support safer launch trajectories over water, reducing risks to populated areas. Overall, the geographical distribution suggests that launch-site selection is influenced by safety, orbital requirements and operational considerations.

In [22]:
# Task 2: Mark the success/failed launches for each site on the map

# TASK 2: Assign marker colours to landing outcomes

spacex_df["marker_color"] = spacex_df["class"].apply(
    lambda outcome: "green" if outcome == 1 else "red"
)

display(
    spacex_df[
        ["Launch Site", "Lat", "Long", "class", "marker_color"]
    ].head()
)

   Launch Site        Lat       Long  class marker_color
0  CCAFS LC-40  28.562302 -80.577356      0          red
1  CCAFS LC-40  28.562302 -80.577356      0          red
2  CCAFS LC-40  28.562302 -80.577356      0          red
3  CCAFS LC-40  28.562302 -80.577356      0          red
4  CCAFS LC-40  28.562302 -80.577356      0          red

In [23]:
from folium.plugins import MarkerCluster

# Create a new map
site_map = folium.Map(
    location=nasa_coordinate,
    zoom_start=5
)

# Create a marker cluster
marker_cluster = MarkerCluster()

# Add the cluster to the map
site_map.add_child(marker_cluster)

site_map

In [24]:
# Add markers for every SpaceX landing outcome

for _, record in spacex_df.iterrows():

    coordinate = [record["Lat"], record["Long"]]

    folium.Marker(
        location=coordinate,
        popup=f"Landing outcome: {record['class']}",
        icon=folium.Icon(
            color=record["marker_color"],
            icon="info-sign"
        )
    ).add_to(marker_cluster)

# Display the completed map
site_map

## Explain your findings

Landing Outcome Analysis

The interactive map displays successful and unsuccessful SpaceX booster landings at different launch sites. Green markers represent successful landings, while red markers represent unsuccessful landings.
Marker clusters help visualise the concentration of launches at each location. By expanding the clusters, we can compare landing outcomes across launch sites and identify patterns in their recorded landing performance.
These observations help us understand the geographical distribution of SpaceX launch activities and landing outcomes.

Important: The markers represent launch records placed at their launch-site coordinates, not the actual geographical locations where the boosters landed.

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [25]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [27]:
# Create a MarkerCluster object
marker_cluster = MarkerCluster()

# Create a marker_color column based on landing success
spacex_df["marker_color"] = spacex_df["class"].apply(
    lambda x: "green" if x == 1 else "red"
)

# Check the result
display(spacex_df[["Launch Site", "class", "marker_color"]].head(10))

   Launch Site  class marker_color
0  CCAFS LC-40      0          red
1  CCAFS LC-40      0          red
2  CCAFS LC-40      0          red
3  CCAFS LC-40      0          red
4  CCAFS LC-40      0          red
5  CCAFS LC-40      0          red
6  CCAFS LC-40      0          red
7  CCAFS LC-40      0          red
8  CCAFS LC-40      0          red
9  CCAFS LC-40      0          red

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

### Explanation
- class = 1 → Green (successful landing).
- class = 0 → Red (unsuccessful landing).
- .apply() checks each value in the class column and assigns the appropriate colour.
- marker_cluster = MarkerCluster() creates a cluster object that we'll use to group markers on the map.
Expected output: A table with a new marker_color column containing green and red.

In [28]:
# Create a new map
site_map = folium.Map(
    location=nasa_coordinate,
    zoom_start=5
)

# Create a MarkerCluster
marker_cluster = MarkerCluster()

# Add the marker cluster to the map
site_map.add_child(marker_cluster)

# Add markers for each launch record
for _, row in spacex_df.iterrows():

    coordinate = [row["Lat"], row["Long"]]

    folium.Marker(
        location=coordinate,
        icon=folium.Icon(
            color=row["marker_color"]
        ),
        popup=f"Landing Class: {row['class']}"
    ).add_to(marker_cluster)

# Display the map
site_map

In [ ]:
# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

#### Expected result
You should see an interactive map with clustered launch records. Click a cluster to expand it and see:
- Green markers — Successful landings.
- Red markers — Failed landings.

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [29]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

### TASK 3: Calculate the distances between a launch site to its proximities

In [30]:
# Show latitude and longitude when moving the mouse over the map

formatter = "function(num) {return L.Util.formatNum(num, 5);};"

mouse_position = MousePosition(
    position="topright",
    separator=" Long: ",
    empty_string="NaN",
    lng_first=False,
    num_digits=20,
    prefix="Lat:",
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

In [31]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [32]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [33]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [ ]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

In [34]:
# Select the launch site
launch_site = launch_sites[
    launch_sites["Launch Site"] == "CCAFS LC-40"
].iloc[0]

# Launch site coordinates
launch_site_lat = launch_site["Lat"]
launch_site_lon = launch_site["Long"]

# Example coastline coordinates
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calculate the distance
distance_coastline = calculate_distance(
    launch_site_lat,
    launch_site_lon,
    coastline_lat,
    coastline_lon
)

print(f"Distance to coastline: {distance_coastline:.2f} km")

Distance to coastline: 0.58 km

In [35]:
# Add a marker at the coastline coordinate
folium.Marker(
    location=[coastline_lat, coastline_lon],
    popup=f"Distance to coastline: {distance_coastline:.2f} km",
    icon=folium.Icon(color="blue")
).add_to(site_map)

# Draw a line from the launch site to the coastline
folium.PolyLine(
    locations=[
        [launch_site_lat, launch_site_lon],
        [coastline_lat, coastline_lon]
    ],
    color="blue",
    weight=3
).add_to(site_map)

# Display map
site_map

In [36]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )

# Coordinates of the selected coastline point
coordinate = [coastline_lat, coastline_lon]

# Create a marker displaying the distance in KM
distance_marker = folium.Marker(
    location=coordinate,
    icon=DivIcon(
        icon_size=(100, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12px; color:#d35400;"><b>%s</b></div>'
        % "{:.2f} KM".format(distance_coastline)
    )
)

# Add the distance marker to the map
site_map.add_child(distance_marker)

# Display the map
site_map

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [38]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)
# site_map.add_child(lines)

# Coordinates of the launch site and coastline
coordinates = [
    [launch_site_lat, launch_site_lon],
    [coastline_lat, coastline_lon]
]

# Create a line connecting the two locations
lines = folium.PolyLine(
    locations=coordinates,
    weight=2,
    color="blue"
)

# Add the line to the map
site_map.add_child(lines)

# Display the map
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [40]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

# Enter coordinates identified on your Folium map
# Replace None with the actual latitude and longitude

nearby_locations = {
    "City": [28.40, -80.60],
    "Railway": [None, None],
    "Highway": [None, None]
}

# Calculate distances and add markers and lines
for location_name, coordinate in nearby_locations.items():

    lat, lon = coordinate

    if lat is None or lon is None:
        print(f"Enter coordinates for {location_name}")
        continue

    distance = calculate_distance(
        launch_site_lat,
        launch_site_lon,
        lat,
        lon
    )

    # Add a distance label
    folium.Marker(
        location=[lat, lon],
        icon=DivIcon(
            icon_size=(160, 25),
            icon_anchor=(0, 0),
            html=(
                f'<div style="font-size:12px; color:#d35400;">'
                f'<b>{location_name}: {distance:.2f} KM</b>'
                f'</div>'
            )
        )
    ).add_to(site_map)

    # Draw a line to the launch site
    folium.PolyLine(
        locations=[
            [launch_site_lat, launch_site_lon],
            [lat, lon]
        ],
        weight=2,
        color="blue"
    ).add_to(site_map)

    print(f"{location_name}: {distance:.2f} KM")

# Display the map
site_map

City: 18.19 KM
Enter coordinates for Railway
Enter coordinates for Highway

Geographical Proximity Analysis

The geographical analysis examines the distances between SpaceX launch sites and nearby coastlines, cities, railways and highways.
Coastal proximity is important because launches over the ocean can reduce risks to populated areas. Access to roads and other transport infrastructure can also support the movement of equipment, materials and personnel.
The analysis helps illustrate how geographical location, safety considerations and accessibility may influence the selection of launch sites.

City: 12.34 KM
Railway: 8.56 KM
Highway: 3.21 KM

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

### Geographical Proximity Analysis — Key Findings

The geographical analysis of SpaceX launch sites suggests several important factors influencing launch-site selection.

1. **Railway proximity:** Some launch sites have access to nearby railway infrastructure, which can support the transportation of heavy equipment and materials.

2. **Highway proximity:** Launch sites generally have access to road networks, supporting the movement of personnel, equipment and supplies.

3. **Coastal proximity:** The launch sites are located near coastlines. This is particularly important for launch safety because rocket trajectories can be directed over the ocean, reducing risks to populated areas.

4. **Distance from cities:** Launch facilities are generally separated from densely populated urban areas to help manage safety risks, although the distances vary by location.

### Conclusion

The geographical locations of SpaceX launch sites reflect a combination of safety, transportation accessibility and operational requirements. Coastal proximity is especially important for supporting launch trajectories over water, while access to transportation infrastructure helps facilitate launch operations.

These observations suggest that geography plays an important role in launch-site selection. However, precise conclusions about the nearest railway, highway and city require verified distance measurements for each launch site.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>